### ISSUE TITLE
Play button is not locked down after activated

### ISSUE THREAD

**Issue by FFY00** [ApolloTVofficial/kamino#1]
When we click on the play button it launches a CPlayer instance. The CPlayer instance needs some time before it's ready, so we are kept on the Movie/Episode preview page. When we are on this page the Play button is still active, allowing us to click again and consequently launching a new CPlayer instance. The button should be deactivated after being clicked.

**Comment by dali546** [comment]
Yh I've noticed that ... It just seems to update the cards with new images... It doesn't regenerate a view. Guess its not too bad though.

But if you are halfway down the list, it doesn't scroll all the way back up. 

As for OPs problem , that should be fixed because there is a sort of alertView popup that says loading...
