### ISSUE TITLE
Sorting sources

### ISSUE THREAD

**Issue by SamJakob** [ApolloTVofficial/kamino#102]
Allow for sorting sources by a variety of criteria.

**Comment by FlyPigsFly** [comment]
Some examples would be...

File size
Provider
Resolver
Quality
Ping (if implemented)
Real Debrid

Also something to think about is various sorting methods at once. For instance I'd like to sort by real debrid and filesize. In other words show me real debrid links first then show me the largest file size of real debrid links first.

**Comment by kevincosmos** [comment]
Just to expand on this:

Currently, the search results are sorted by response time (ms), I would propose an option in settings to set "preferred hosts" so that if a user knows that they get no buffering from GorrilaVid as example, they can set it as preferred and those will be sorted first and potentially have the white icon on the left of the search results change to a star to indicate it is preferred.

To expand upon this, the user could  single-tap the host in the list to "like" it and double-tap the host to "dislike" to signify they don't want to see results or have them at the bottom of the list (many countries block openload, so people may choose to hide those links or have them at the bottom of results)

**Comment by kevincosmos** [comment]
Further to my above point, the UI of the host preference would be similar to rearranging the launchpad cards, you can move the list around to suit your preferences.

Example of how this would work:

My default sort order for search results is by Quality (1080P). I search for The Walking Dead and it pulls 50 results from 4 of those sources which meets my 1080P criteria. In my settings, I have selected "Openload" as my top preferred host, so those 1080P links are further sorted by the order of my preferred hosts, showing my Openload links first.

By default, preferred hosts would be turned off, and only come into effect when someone wants to specify the order of hosts they like.

**Comment by NBTX** [comment]
This has been implemented with the metadata that we currently have.

![image](https://user-images.githubusercontent.com/43181178/55693009-9755c500-59a4-11e9-898d-663ae5413619.png)
