### ISSUE TITLE
[Request] - Adjustable/Auto Time Zone for "Airing Today" category

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#110]
The "Airing Today" category will update to list shows for the following day for those of us in different timezones like PST. It would be cool if we could continue to display shows so late night/end of the day browsing could be possible for shows that have aired but might not be favorites.

**Comment by SpajicM** [comment]
This can be done but it may not achieve what you expect.
TMDB supports adjustment by timezone, but doesn't check show by airing time.

Meaning, if you put it to your timezone, and a show is set to air on February 16th US evening time, it won't show you that show until it's 16th at your place.
Similarily, if it's 16th at your place, and a show is premiering somewhere where it's not 16th yet, you would have the show listed, but have absolutely no sources, since show didn't air yet :)

TMDB API docs: https://developers.themoviedb.org/3/tv/get-tv-airing-today
Example: https://www.themoviedb.org/talk/55b922b092514123df0025a7

**Comment by NBTX** [comment]
Given that, as @SpajicM has stated; the behavior is not intuitive, would you still like us to implement this?

**Comment by JLDevUsr** [comment]
I think having the option to adjust the time zone is important. I didn't really understand too well what @SpajicM meant above but I think the feature would still be nice if implemented; however, I think that something like #109 / #88 would negate the need for a timezones implementation. Rather someone could go to a "Continue Watching" section and view all of the shows that can be watched next/ that might have aired that day to continue watching.

**Comment by NBTX** [comment]
Okay, I'm closing this in favor of replacing it with a 'Watch next' and 'Continue watching' cards.
