### ISSUE TITLE
Finish Chromecast implementation

### ISSUE THREAD

**Issue by nickrts22** [ApolloTVofficial/kamino#14]
App will not cast anything once a device is selected. (Sidenote) devices take a long time to show up after tapping the cast button

**Comment by NBTX** [comment]
Both of these are known issues but I'll keep this issue open and update you on progress.

**Comment by kevincosmos** [comment]
![image](https://user-images.githubusercontent.com/30179692/53241134-a7d20a80-3698-11e9-8ac2-d4e002a43a6e.png)

**Comment by corkiejp** [comment]
Posting here instead of creating new suggestion/issue?

For using chromecast it would be handy to display the file type in source list.
Not all media is supported for direct casting.
Only mp4/avi  and mkv (wrapper with previous file types).

Alternatively a filter option to only display sources that maybe supported when the cast button has already been selected?

**Comment by NBTX** [comment]
Chromecast is implemented and as per @corkiejp's request, we are now showing the file type in the source list.
