### ISSUE TITLE
[Idea/Request] - Next season swipe

### ISSUE THREAD

**Issue by JLDevUsr** [ApolloTVofficial/kamino#246]
When in a season of a show, if you drag from the far right edge of your screen to the left the page would transition to list episodes from being in (for example) season 2 to season 3. In the same way swiping left to right would go from (for example) season 3 to season 2.

**Comment by JLDevUsr** [comment]
An alternative to this would be similar to Netflix. When you scroll down there would be a definitive change at the top of the screen or somewhere within view to identify that the season has changed. I'd move up an image for this but I'm currently away fro  home.

**Comment by Rowan-Paul** [comment]
Or something similar to the YouTube app in fullscreen mode where you'd pull up and see the next episodes?

**Comment by JLDevUsr** [comment]
That would be regarding the player and actual episodes being watched. This issue is regarding the process of chosing an episode. From multiple seasons without having to go back to swap seasons.

**Comment by NBTX** [comment]
That's a pretty nice way of handling it to be honest, I think I'll try implementing it this way.

**Comment by dscre** [comment]
I'd suggest to go one step further and implement the gesture/navigation to the who app. i.e. on all pages wherever possible, so that browsing a particular catalogue becomes easier.

For eg: If I'm on a series page (but not in the seasons page), swiping should take me to the previous/next series on the list from where I came. i.e. if I go from "Series">"Adventure list">"Series05", then by swiping left/right I should be able to browse the whole "Adventure" catalogue present in the list.

**Comment by dscre** [comment]
I'd suggest to go one step further and implement that gesture/navigation to the whole app. i.e. on all pages wherever possible, so that browsing a particular catalogue becomes easier.

For eg: If I go from List > Series Page (but not in the Seasons Page), swiping should take me to the previous/next series on the list from where I came. i.e. if I go from "Series">"Adventure list">"Series05", then by swiping left/right I should be able to browse  Series04, Series03... etc  ...the whole "Adventure" catalogue present in the list.

**Comment by NBTX** [comment]
I've implemented a season selector in the title bar for seasons, so I'll close this issue. I didn't end up using swiping because the season information has to load and I felt the selector was the best UX as a result of that.

At least for seasons, I figured it wasn't that big a deal as you won't switch seasons nearly as much as you switch episodes; (I am going to revisit this idea for the episode screen.)
