### ISSUE TITLE
Sources auto-selection improvement

### ISSUE THREAD

**Issue by SpajicM** [ApolloTVofficial/kamino#62]
Manual source selection should be an option, but I have some idea's how to improve autoselect too.

I think one of key reasons why people buy Netflix is fast loading even on slow connection, there's no resolution selection at all.

My suggestion is this:

When application is started, make a speed test of the user's connection in the background.

When movie or TV show is selected, take previously measured user's internet connection, server response speed, file size (Metadata idea mentioned by deathbysnoosnoo in discord) and calculate a "best choice" for 360p, 480p, 720p...

Pass on those to player, so it's possible to have a resoution picker similar to YouTube.

This could greatly improve UX compared to quitting what you are watching to select a different source.

**Comment by F3ttL0rd** [comment]
An auto selection mode for the average user is fine, but I would very much like a pro mode/manual selection that gives me as much information as possible about the selected source. Full file name, used video/audio codecs, file size, etc.

Simple reason for this is my Sonos playbar. Sources with DTS codec won't bring me any joy since I won't hear any sound. Therefore I would always select my sources manually and don't mind the extra step. This should be a general option in the settings menu.

Thoughts?

**Comment by SpajicM** [comment]
Of course, this was not meant to cripple any "pro" data view or manual selection, it's just my suggestion for having some logic behind the auto source selection rather than it being a sources response race as it is now

**Comment by kevincosmos** [comment]
Closing this and linking to #107
