### ISSUE TITLE
QOL Suggestions - General

### ISSUE THREAD

**Issue by kevincosmos** [ApolloTVofficial/kamino#91]
- Have build number "i.e. 1.2.0" on splash screen

Not sure if these are possible based on @edmundackah's replies in Discord:

- Sort by > "Release Date/Descending" inside Movies/TV Shows bring shows that are airing in 2025 etc, logically it shouldn't go beyond current day or year since there will be no links. Alternatively, you could change the "Play Movie" button to "Not Released", but I think anything coming out after the current day or possibly year should be hidden.

- Sort by > "Vote Average/Decending" shows films with only a few 5 star ratings at top. As a proposed resolution, maybe change the voting to be average per (X) users? X can be 100/500/1000?

**Comment by kevincosmos** [comment]
Can a dev comment on this? It's been open for over a month.

If these aren't going to be possible, issue can be closed.

**Comment by NBTX** [comment]
- Have build number "i.e. 1.2.0" on splash screen
No. (We discussed this before, it's not really worth the effort.)

<hr>

- Sort by > "Release Date/Descending" inside Movies/TV Shows bring shows that are airing in 2025 etc, logically it shouldn't go beyond current day or year since there will be no links. Alternatively, you could change the "Play Movie" button to "Not Released", but I think anything coming out after the current day or possibly year should be hidden.

Proposed solution: hide anything not yet released.

<hr>

- Sort by > "Vote Average/Descending" shows films with only a few 5 star ratings at top. As a proposed resolution, maybe change the voting to be average per (X) users? X can be 100/500/1000?

Okay. Should this voting average be in Settings and how should we handle movies that are lower than this average? Consider votes for all users from vote count to X to be 0?

**Comment by kevincosmos** [comment]
Closing this to open individual issues for easier tracking.
